# a really bad stubbed makefile, will fix later. 
CC:=gcc
CFLAGS:= -pthread

concurrency1:
	$(CC) concurrency1.c $(CFLAGS) -o concurrency1

clean:
	rm concurrency1

submission:
	tar cvjf CS444-mouldsm-concurrency1.tar.bz2 ./README ./concurrency1.c ./Makefile
